all:
  children:
    webservers:
      hosts:
        ubuntu-18:
          ansible_host: 192.168.121.30
          ansible_user: bahrom
          ansible_become: true
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        centos-8:
          ansible_host: 192.168.121.31
          ansible_user: bahrom
          ansible_become: true
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
