all:
  children:
    webservers:
      hosts:
        ubuntu-18:
          ansible_host: 192.168.121.30
          ansible_user: ansible
          ansible_become: true
        centos-8:
          ansible_host: 192.168.121.31
          ansible_user: ansible
          ansible_become: true
        ubuntu-24:
          ansible_host: 192.168.120.214
          ansible_user: ansible
          ansible_become: true
