---
- name: Converge
  hosts: all
  become: true
  vars:
    users_users:
      - name: deploy
        shell: /bin/bash
        sudo: true
        ssh_keys:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMoleculeTestKeyDoNotUseInProduction deploy@molecule"
      - name: appuser
        sudo: false
  roles:
    - role: users
