---
users_users:
  - name: ansible
    sudo: true
    ssh_keys:
      - bahrom

  - name: ahmad
    sudo: true
    ssh_keys:
      - ahmad

  - name: sardor.ergashev
    sudo: true
    ssh_keys:
      - sardor.ergashev

  - name: zokir
    sudo: true
    ssh_keys:
      - zokir

  - name: abbos
    sudo: true
    ssh_keys:
      - abbos

  - name: bahrom
    sudo: true
    ssh_keys:
      - bahrom

  - name: takhir
    sudo: true
    ssh_keys:
      - takhir

users_passwords: "{{ vault_user_passwords | default({}) }}"
users_prune_unmanaged: true
users_prune_keep: [ ]
users_default_shell: /bin/zsh
users_create_home: true
users_force_password_change: false
users_ssh_keys_dir: "{{ playbook_dir }}/../files/ssh_keys"
users_zsh_setup: true
users_zsh_theme: "dieter"
users_zsh_plugins:
  - git
  - zsh-autosuggestions
  - zsh-syntax-highlighting
users_zsh_ohmyzsh_dir: "{{ zsh_ohmyzsh_dir | default('/usr/share/oh-my-zsh') }}"
