---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  tags: [basic, basic_timezone, basic_packages]

- name: Configure timezone
  ansible.builtin.include_tasks: timezone.yml
  tags: [basic, basic_timezone]

- name: Install base packages
  ansible.builtin.include_tasks: packages.yml
  tags: [basic, basic_packages]
